name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Cloner le repo
        uses: actions/checkout@v3

      - name: 🔧 Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Construire l'image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/livre-or ./website

      - name: 🚀 Pusher l'image sur DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/livre-or

